Rails/Assignment1/config/routes.rb
Assignment1::Application.routes.draw do
  get "user/first_name"
  get "user/last_name"
  get "user/password"
  get "user/newsletter"
  resources :editorials

  devise_for :users
  resources :reviews
  resources :products do
    resources :reviews
  end

  resources :blogs do
    resources :comments
  end

  get 'editorial/:id/mail' => 'editorials#mail', :as => 'email_editorial'
  get 'editorial/:id/spam' => 'editorials#spam', :as => 'spam_editorial'

  get 'store/index'
  get 'store/show/:id' => 'store#show', :as => 'store_show'
  get 'about'  => 'page#about'
  get 'calendar(/:year(/:month))' => 'page#calendar', :as =>'calendar'
  match 'contact'  => 'page#contact', :via => [:post, :get]
  get 'index' => 'page#index'
  get 'login'  => 'page#login'
  get 'preferences' => 'page#preferences'

  root 'page#index'

end

Rails/Assignment1/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # POST /reviews
  # POST /reviews.json
  def create
    @product = Product.find(params[ :product_id])
    @review = @product.reviews.new( review_params )

    respond_to do |format|
      if @review.save
        format.html { redirect_to store_show_path( @product ), notice: 'Review was successfully created.' }
        format.json { render action: 'show', status: :created, location: @review }
      else
        format.html { redirect_to store_show_path( @product ), notice: 'Review was NOT successfully created.' }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end
  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to product_path(@review.product_id ) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:name, :content, :rating, :product_id)
    end
end

Rails/Assignment1/app/helpers/reviews_helper.rb
module ReviewsHelper
end

Rails/Assignment1/app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.number_field :rating %>
  </div>
  <div class="field">
    <%= f.label :product %><br>
    <%= f.text_field :product %>
  </div>
    <div class="field">
      <%= f.label :created_at %><br>
      <%= f.timestamp :created_at %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Rails/Assignment1/app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', products_path %>

Rails/Assignment1/app/views/reviews/index.html.erb
<h1>Listing reviews</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Content</th>
      <th>Rating</th>
      <th>Product</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.name %></td>
        <td><%= review.content %></td>
        <td><%= review.rating %></td>
        <td><%= review.product %></td>
        <td><%= review.created_at %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

Rails/Assignment1/app/views/reviews/new.html.erb
<h1>New review</h1>

<%= render 'form' %>

<%= link_to 'Back', reviews_path %>

Rails/Assignment1/app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Created:</strong>
  <%= @review.created_at %>
</p>
<p>
  <strong>Name:</strong>
  <%= @review.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @review.content %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @review.rating %>
</p>


<%= link_to 'Back', store_index_path %>