Rails/Assignment1/config/routes.rb
Assignment1::Application.routes.draw do
  get "user/first_name"
  get "user/last_name"
  get "user/password"
  get "user/newsletter"
  resources :editorials

  devise_for :users
  resources :reviews
  resources :products do
    resources :reviews
  end

  resources :blogs do
    resources :comments
  end

  get 'editorial/:id/mail' => 'editorials#mail', :as => 'email_editorial'
  get 'editorial/:id/spam' => 'editorials#spam', :as => 'spam_editorial'

  get 'store/index'
  get 'store/show/:id' => 'store#show', :as => 'store_show'
  get 'about'  => 'page#about'
  get 'calendar(/:year(/:month))' => 'page#calendar', :as =>'calendar'
  match 'contact'  => 'page#contact', :via => [:post, :get]
  get 'index' => 'page#index'
  get 'login'  => 'page#login'
  get 'preferences' => 'page#preferences'

  root 'page#index'

end

Rails/Assignment1/app/models/blog.rb
class Blog < ActiveRecord::Base
  has_many :comments, :dependent => :destroy
  validates_presence_of :title, :author, :content
  validates :date, numericality: { only_integer: true }
  paginates_per 5
end

Rails/Assignment1/app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @page = params[ 'page']
    @blogs = Blog.page(@page).order( :updated_at => :desc )
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @comment = Comment.new
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render action: 'show', status: :created, location: @blog }
      else
        format.html { render action: 'new' }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :author, :date, :content)
    end
end

Rails/Assignment1/app/helpers/blogs_helper.rb
module BlogsHelper
end

Rails/Assignment1/app/views/blogs/_form.html.erb
<%= tinymce %>
<%= form_for(@blog) do |f| %>
    <% if @blog.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

          <ul>
            <% @blog.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class='align'>
      <div class="field">
        <%= f.label :title %><br>
        <%= f.text_field :title %>
      </div>
      <div class="field">
        <%= f.label :author %><br>
        <%= f.text_field :author %>
      </div>
      <div class="field">
        <%= f.label :date %><br>
        <%= f.number_field :date, :in => (1930..2013) %>
      </div>
      <div class="field">
        <%= f.label :content %><br>
        <%= f.text_area :content, :class => 'tinymce' %>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
    </div>
<% end %>

Rails/Assignment1/app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>
<%= tinymce_assets %>
<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

Rails/Assignment1/app/views/blogs/index.html.erb
<h1>Blogs</h1>
<%= link_to 'New Blog', new_blog_path %>
<%= paginate @blogs %>
<table>

  <tr>
    <th>Title</th>
    <th>Author</th>
    <th>Date</th>
    <th>Content</th>
    <% if current_user.try( :admin? ) %>
        <th colspan=3>Functions</th>
    <% else %>
        <th>Show</th>
    <%end %>
  </tr>



  <% @blogs.each do |blog| %>
      <tr>
        <%#= time_ago_in_words(blog.date) %>
        <td style='width:200px;'><%= blog.title %></td>
        <td style='width:150px;'><%= blog.author %></td>
        <td style='width:20px;'><%= blog.date %></td>
        <td><%= blog.content.html_safe %></td>
        <td style='width:30px;'><%= link_to 'Show', blog %></td>
        <% if current_user.try( :admin? ) %>
            <td style='width:30px;'><%= link_to 'Edit', edit_blog_path(blog) %></td>
            <td style='width:30px;'><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
  <% end %>

</table>

<br>

Rails/Assignment1/app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>

Rails/Assignment1/app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Back to Blogs Table', blogs_path %> <br/><br/>
<section class='align'>
  <strong>Average Rating:  </strong>
  <% if @blog.comments.average(:rating) != nil %>
      <%= stars( @blog.comments.average(:rating).round) %><br/> <br/>
  <% end %>
  <strong>Created:</strong>
  <%= time_ago_in_words(@blog.created_at) %> ago<br/> <br/>

  <strong>author:</strong>
  <%= @blog.author %><br/> <br/>
  <strong>Title:</strong>
  <%= @blog.title %><br/> <br/>
  <strong>Content:</strong>
  <%= @blog.content.html_safe %><br/><br/>

  <% if current_user.try( :admin? ) %>
      <%= link_to 'Edit Blog', edit_blog_path(@blog) %>
  <% end %>
</section>
<h2 class='pagination'>Blog comments:</h2>
<% @blog.comments.each do |comment| %>
    <h3><%= time_ago_in_words(comment.created_at) %> ago,</h3>
    <h3><%= image_tag comment.image, :class=>'avatar' %>  <%= comment.author %> said:</h3>
    <h4>&nbsp;&nbsp;&nbsp;&nbsp;<%= comment.content %></h4>
    <h3><%= stars(comment.rating) %></h3>

    <% if is_admin? %>
        <h5><%= link_to 'Delete comment', blog_comment_path( @blog, comment), :confirm => 'Confirm delete?', :method => :delete %></h5>
    <% end %>
    <hr>
<% end %>

<%= form_for([@blog, @comment] ) do |f| %>
    <% if @comment.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

          <ul>
            <% @comment.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :author %><br>
      <%= f.text_field :author %>
    </div>
    <div class="field">
      <%= f.label :content %><br>
      <%= f.text_area :content %>
    </div>
    <div class="field">
      <%= f.label :image %><br>
      <%= f.text_area :image %>
    </div>
    <div class="field">
      <%= f.label :rating %><br>
      <%= f.number_field :rating, :in => 1..5 %>
    </div>
    <%= f.hidden_field :blog %>


    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>