Rails/Assignment1/config/routes.rb
Assignment1::Application.routes.draw do
  get "user/first_name"
  get "user/last_name"
  get "user/password"
  get "user/newsletter"
  resources :editorials

  devise_for :users
  resources :reviews
  resources :products do
    resources :reviews
  end

  resources :blogs do
    resources :comments
  end

  get 'editorial/:id/mail' => 'editorials#mail', :as => 'email_editorial'
  get 'editorial/:id/spam' => 'editorials#spam', :as => 'spam_editorial'

  get 'store/index'
  get 'store/show/:id' => 'store#show', :as => 'store_show'
  get 'about'  => 'page#about'
  get 'calendar(/:year(/:month))' => 'page#calendar', :as =>'calendar'
  match 'contact'  => 'page#contact', :via => [:post, :get]
  get 'index' => 'page#index'
  get 'login'  => 'page#login'
  get 'preferences' => 'page#preferences'

  root 'page#index'

end

Rails/Assignment1/app/views/shared/_nav.html.erb
<nav>
  <ul id='nav'>
    <li>
      <%= link_to 'Home', index_path %>
      <%= link_to 'About Us', about_path %>
      <%= link_to 'Articles', editorials_path %>
      <%= link_to 'Blogs', blogs_path %>
      <%= link_to 'Calendar', calendar_path %>
      <%= link_to 'Contact Us', contact_path %>
      <% if user_signed_in? %>
          <%= link_to 'Products', products_path %>
          <%= link_to 'Preferences', edit_user_registration_path %>
          <%= link_to 'LogOut', destroy_user_session_path, :method => :delete %>
      <% else %>
          <%= link_to 'Products', store_index_path %>
          <%= link_to 'LogIn', new_user_session_path %>
      <% end %>

    </li>
  </ul>
</nav>
<% if user_signed_in? %>
    <h2 class='error'>Logged in as: <%= current_user.full_name %></h2><br/>
<% end %>