Rails/Assignment1/config/routes.rb
Assignment1::Application.routes.draw do
  get "user/first_name"
  get "user/last_name"
  get "user/password"
  get "user/newsletter"
  resources :editorials

  devise_for :users
  resources :reviews
  resources :products do
    resources :reviews
  end

  resources :blogs do
    resources :comments
  end

  get 'editorial/:id/mail' => 'editorials#mail', :as => 'email_editorial'
  get 'editorial/:id/spam' => 'editorials#spam', :as => 'spam_editorial'

  get 'store/index'
  get 'store/show/:id' => 'store#show', :as => 'store_show'
  get 'about'  => 'page#about'
  get 'calendar(/:year(/:month))' => 'page#calendar', :as =>'calendar'
  match 'contact'  => 'page#contact', :via => [:post, :get]
  get 'index' => 'page#index'
  get 'login'  => 'page#login'
  get 'preferences' => 'page#preferences'

  root 'page#index'

end

Rails/Assignment1/app/models/product.rb
class Product < ActiveRecord::Base
  has_many :reviews, :dependent => :destroy
  validates_presence_of :name, :description, :thumbnail, :fullsize
  validates_numericality_of :price, :cost, :weight
  validates :qty, numericality: { only_integer: true }
  paginates_per 5
end

Rails/Assignment1/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate, except: [ :index, :show ]
  # GET /products
  # GET /products.json
  def index
    @page1 = params[ 'page']
    #@previous2 = @page2 - 1 unless @page2 == 0
    #@next2 = @page2 + 1 unless @page2 * 5 > Product.count
    @products = Product.page(@page1).order( :updated_at => :desc )
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @review = Review.new
    @product = Product.find( params[ :id ])
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :qty, :price, :cost, :weight, :thumbnail, :fullsize)
    end
  def authenticate
    authenticate_user! && current_user.try( :admin? )
  end
end

Rails/Assignment1/app/helpers/products_helper.rb
module ProductsHelper
end

Rails/Assignment1/app/views/products/_form.html.erb
<%= tinymce %>
<section class = 'align'>
  <%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, :class => 'tinymce' %>
  </div>
  <div class="field">
    <%= f.label :qty %><br>
    <%= f.number_field :qty %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :cost %><br>
    <%= f.text_field :cost %>
  </div>
  <div class="field">
    <%= f.label :weight %><br>
    <%= f.text_field :weight %>
  </div>
  <div class="field">
    <%= f.label :thumbnail %><br>
    <%= f.text_field :thumbnail %>
  </div>
  <div class="field">
    <%= f.label :fullsize %><br>
    <%= f.text_field :fullsize %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>
</section>

Rails/Assignment1/app/views/products/edit.html.erb
<h1>Editing product</h1>
<%= tinymce_assets %>
<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

Rails/Assignment1/app/views/products/index.html.erb
<h1>Inventory</h1>

<%= paginate @products %>
<table class='plain'>
  <thead>
    <tr>
      <th> ID No:</th>
      <th>Name</th>
      <th>Description</th>
      <th>Qty</th>
      <th>Price</th>
      <% if current_user.try( :admin? ) %>
        <th>Cost</th>
      <% end %>
      <th>Weight</th>
      <th>Thumbnail</th>
      <th colspan=3>Functions</th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.id %></td>
        <td><%= link_to product.name, product %></td>
        <td class='wide'><%= product.description.html_safe %></td>
        <%#= truncate(product.description, :length => 20).html_safe %>
        <td><%= product.qty %></td>
        <td><%= product.price %></td>
        <% if current_user.try( :admin? ) %>
        <td><%= product.cost %></td>
        <% end %>
        <td><%= product.weight %></td>
        <td><%= link_to(image_tag(product.thumbnail, :class=> 'imgsmall'), product) %></td>
        <td><%= link_to 'Show', product %></td>
        <% if current_user.try( :admin? ) %>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
       <% end %>
  </tbody>
</table>

<br><% if current_user.try( :admin? ) %>
        <%= link_to 'Add New Product', new_product_path %>
    <% end %>

Rails/Assignment1/app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

Rails/Assignment1/app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

  <%= link_to 'Back to Products Table', products_path %> <br/><br/>
<section class='align'>
  <strong>Average Rating:  </strong><%= stars( @product.reviews.average(:rating).round) %><br/> <br/>
  <strong>Name:</strong>
  <%= @product.name %><br/> <br/>



  <strong>Description:</strong>
  <%= @product.description.html_safe %><br/><br/>



  <strong>Qty:</strong>
  <%= @product.qty %><br/> <br/>



  <strong>Price:</strong>
  <%= @product.price %><br/> <br/>

<% if current_user.try( :admin? ) %>

  <strong>Cost:</strong>
  <%= @product.cost %>  <br/> <br/>

<% end %>

  <strong>Weight:</strong>
  <%= @product.weight %>  <br/> <br/>
  <strong>Fullsize Image:</strong>
  <%= image_tag @product.fullsize, :class=>'imglarge' %> <br/> <br/>
  <% if current_user.try( :admin? ) %>
      <%= link_to 'Edit Product', edit_product_path(@product) %>
  <% end %>
</section>
<h2 class='pagination'>Product Reviews:</h2>
<% @product.reviews.descending.each do |review| %>
    <h3><%= time_ago_in_words(review.created_at) %>ago,</h3>
    <h3><%= review.name %> said:</h3>
    <h4>&nbsp;&nbsp;&nbsp;&nbsp;<%= review.content %></h4>
    <h3><%= stars(review.rating) %></h3>
    <% if is_admin? %>
        <h5><%= link_to 'Delete Review', product_review_path( @product, review), :confirm => 'Confirm delete?', :method => :delete %></h5>
    <% end %>
    <hr>
<% end %>